namespace KleinCompiler
{
    public enum Symbol
    {
        // Error 
        LexicalError,
        // End of tokens marker 
        End,
        // Non Terminals
        Program,          
        DefTail,          
        Def,              
        Formals,          
        NonEmptyFormals,  
        FormalTail,      
        Formal,           
        Body,               
        Type,               
        Expr,               
        SimpleExprTail,     
        SimpleExpr,        
        TermTail,           
        Term,               
        FactorTail,         
        Factor,             
        Func,                
        FuncTail,            
        Actuals,            
        NonEmptyActuals,    
        ActualsTail,        
        Literal,            
        Print,                   
        // Tokens / Terminals
        LineComment,
        BlockComment,
        Identifier,
        IntegerLiteral,
        BooleanTrue,
        BooleanFalse,
        IntegerType,
        BooleanType,
        If,
        Then,
        Else,
        Not,
        Or,
        And,
        Plus,            
        Minus,           
        Multiply,        
        Divide,          
        LessThan,        
        Equality,        
        OpenBracket,     
        CloseBracket,    
        Comma,           
        Colon,
        PrintKeyword,
    }
}