namespace KleinCompiler
{
    public enum Symbol
    {
        // Error 
        LexicalError,
        // End of tokens marker 
        End,
        // Non Terminals
        Program,          
        DefTail,          
        Def,              
        Formals,          
        NonEmptyFormals,  
        FormalTail,      
        Formal,           
        Body,               
        Type,               
        Expr,               
        SimpleExprTail,     
        SimpleExpr,        
        TermTail,           
        Term,               
        FactorTail,         
        Factor,             
        Func,                
        FuncTail,            
        Actuals,            
        NonEmptyActuals,    
        ActualsTail,        
        Literal,            
        Print,                   
        // Tokens / Terminals
        LineComment,
        BlockComment,
        Identifier,
        IntegerLiteral,
        [Keyword("true")]
        BooleanTrue,
        [Keyword("false")]
        BooleanFalse,
        [Keyword("integer")]
        IntegerType,
        [Keyword("boolean")]
        BooleanType,
        [Keyword("if")]
        If,
        [Keyword("then")]
        Then,
        [Keyword("else")]
        Else,
        [Keyword("not")]
        Not,
        [Keyword("or")]
        Or,
        [Keyword("and")]
        And,
        [Keyword("+")]
        Plus,            
        [Keyword("-")]
        Minus,           
        [Keyword("*")]
        Multiply,        
        [Keyword("/")]
        Divide,          
        [Keyword("<")]
        LessThan,        
        [Keyword("=")]
        Equality,        
        [Keyword("(")]
        OpenBracket,     
        [Keyword(")")]
        CloseBracket,    
        [Keyword(",")]
        Comma,           
        [Keyword(":")]
        Colon,
        [Keyword("print")]
        PrintKeyword,
    }
}